#!/bin/bash

set -e
export CC=gcc

echo "===> Installing gem deps.."

bundle pack
bundle install --path vendor/cache
bundle check --path vendor/gems 2>&1 > /dev/null || {
    bundle install --binstubs bin --path vendor/gems --local --quiet
}
